import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { delayReasons } from "@/data/delay-reasons/delayReasons";
import { buildLanguageAlternates, delayReasonSeoLocales } from "@/lib/seo/alternates";
import { buildSwedishDelayReason } from "@/lib/localization/delay-reason-sv";
import { buildDanishDelayReason } from "@/lib/localization/delay-reason-da";
const SITE_URL = "https://www.flightclaimly.com";
type PageProps = { params: Promise<{ locale: string }> };
export async function generateMetadata({ params }: PageProps): Promise<Metadata> { const { locale } = await params; if (!delayReasonSeoLocales.includes(locale as (typeof delayReasonSeoLocales)[number])) return {}; const canonical = `${SITE_URL}/${locale}/delay-reasons`; const sv = locale === "sv"; const da = locale === "da"; const title = sv ? "Orsaker till flygförseningar och ersättning | FlightClaimly" : da ? "Årsager til flyforsinkelser og kompensation | FlightClaimly" : "Flight delay reasons and compensation | FlightClaimly"; const description = sv ? "Läs om vanliga orsaker till flygförseningar och inställda flyg och när ersättning enligt EU261 kan bli aktuell." : da ? "Læs om almindelige årsager til flyforsinkelser og aflysninger, og hvornår kompensation efter EU261 kan være relevant." : "Explore common reasons for flight delays and cancellations and learn when EU261 compensation may apply."; return { title, description, alternates: { canonical, languages: buildLanguageAlternates("delay-reasons", delayReasonSeoLocales) }, openGraph: { title, description, url: canonical, siteName: "FlightClaimly", locale, type: "website" } }; }
export default async function DelayReasonsIndexPage({ params }: PageProps) { const { locale } = await params; if (!delayReasonSeoLocales.includes(locale as (typeof delayReasonSeoLocales)[number])) notFound(); const sv = locale === "sv"; const da = locale === "da"; return <main className="min-h-screen bg-slate-50 px-6 py-20"><section className="mx-auto max-w-5xl"><p className="text-sm font-semibold uppercase tracking-widest text-emerald-600">{sv ? "Kunskap om flygstörningar" : da ? "Viden om flyforstyrrelser" : "Flight disruption knowledge"}</p><h1 className="mt-4 text-4xl font-bold tracking-tight text-slate-950 md:text-5xl">{sv ? "Orsaker till flygförseningar och ersättning" : da ? "Årsager til flyforsinkelser og kompensation" : "Flight delay reasons and compensation"}</h1><p className="mt-6 max-w-3xl text-lg text-slate-700">{sv ? "Utforska vanliga orsaker till förseningar och inställda flyg, hur EU261 behandlar dem och när passagerare kan ha rätt till ersättning." : da ? "Udforsk almindelige årsager til forsinkelser og aflysninger, hvordan EU261 behandler dem, og hvornår passagerer kan have ret til kompensation." : "Explore common causes of flight delays and cancellations, how EU261 treats them, and when passengers may be entitled to compensation."}</p><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{delayReasons.map((reason) => { const item = sv ? buildSwedishDelayReason(reason) : da ? buildDanishDelayReason(reason) : reason; return <Link key={reason.slug} href={`/${locale}/delay-reasons/${reason.slug}`} className="rounded-2xl border bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-md"><h2 className="text-xl font-bold text-slate-950">{item.title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{item.description}</p><p className="mt-5 text-sm font-semibold text-sky-700">{sv ? "Visa ersättningsguide →" : da ? "Se kompensationsguide →" : "View compensation guide →"}</p></Link>; })}</div></section></main>; }
