import { buildLoaDoc } from "@/lib/authority/loa";

type Props = {
  searchParams: Promise<{
    fullName?: string;
    bookingReference?: string;
    claimId?: string;
    final?: string;
    signature?: string;
  }>;
};

export default async function PowerOfAttorneyPage({
  searchParams,
}: Props) {
  const sp = await searchParams;

  const fullName = sp.fullName || "Preview Passenger";
  const bookingReference = sp.bookingReference || "ABC123";
  const claimId = sp.claimId;
  const isFinal = sp.final === "true";
  const signatureUrl = sp.signature || null;
  const today = new Date().toISOString().split("T")[0];

  const { title, metaLines, bodyLinesEN, bodyLinesES } = buildLoaDoc({
    fullName,
    bookingReference,
    claimId,
  });

  return (
    <div
      className={
        isFinal
          ? "bg-white font-[system-ui]"
          : "min-h-screen bg-slate-100 py-8 px-3 font-[system-ui]"
      }
    >
      <div className="mx-auto max-w-[980px] bg-white shadow-xl rounded-lg overflow-hidden text-[11px] leading-[1.22]">
        <div className="bg-gradient-to-r from-[#0F172A] to-[#1E3A8A] px-6 py-5">
          <div className="flex items-center justify-between">
            <img
              src="/logo-flightclaimly.svg"
              alt="FLIGHTCLAIMLY"
              className="h-6"
            />
            <div className="text-xs tracking-widest text-white/70 uppercase">
              Authority Document
            </div>
          </div>
        </div>

        <div className="px-6 py-6">
          <h1 className="text-lg font-semibold text-slate-900 mb-4">
            {title}
          </h1>

          <div className="mb-5 space-y-[2px] text-[11px] text-slate-700">
            {metaLines.map((line, i) => (
              <div key={i}>{line}</div>
            ))}
          </div>

          <div className="grid grid-cols-2 gap-5 text-[9.8px] leading-[1.14] text-slate-800">
            <div>
              <div className="font-semibold text-slate-900 mb-2">English</div>
              {bodyLinesEN.map((line, i) =>
                line.trim() === "" ? (
                  <div key={i} className="h-[4px]" />
                ) : (
                  <p
                    key={i}
                    className={
                      /^\d+\./.test(line)
                        ? "font-semibold text-slate-900 mt-2"
                        : "mt-[2px]"
                    }
                  >
                    {line}
                  </p>
                )
              )}
            </div>

            <div>
              <div className="font-semibold text-slate-900 mb-2">Español</div>
              {bodyLinesES.map((line, i) =>
                line.trim() === "" ? (
                  <div key={i} className="h-[4px]" />
                ) : (
                  <p
                    key={i}
                    className={
                      /^\d+\./.test(line)
                        ? "font-semibold text-slate-900 mt-2"
                        : "mt-[2px]"
                    }
                  >
                    {line}
                  </p>
                )
              )}
            </div>
          </div>

          <div className="mt-6 pt-4 border-t border-slate-200">
            <div className="grid grid-cols-2 gap-6">
              <div>
                <div className="text-[11px] text-slate-700 mb-[2px]">
                  Passenger Signature
                </div>

                <div className="h-14 border border-slate-300 rounded bg-slate-50 flex items-center px-2 overflow-hidden">
                  {isFinal && signatureUrl ? (
                    <img
                      src={signatureUrl}
                      alt="Passenger signature"
                      className="h-12 max-w-full object-contain mx-auto"
                      style={{ filter: "contrast(1.15)" }}
                    />
                  ) : null}
                </div>

                <div className="text-[9px] text-slate-500 mt-[2px]">
                  {isFinal ? fullName : "Signature will appear here"}
                </div>
              </div>

              <div>
                <div className="text-[11px] text-slate-700 mb-[2px]">
                  Date
                </div>

                <div className="h-10 flex items-center px-3 border border-slate-300 rounded bg-slate-50 text-[11px] text-slate-700">
                  {today}
                </div>
              </div>
            </div>

            <div className="text-[9px] text-slate-400 mt-3">
              Document generated by FlightClaimly claim system • EU Regulation
              261/2004
            </div>
          </div>

          {!isFinal && (
            <div className="mt-6 pt-4 border-t border-slate-200 text-[11px] text-slate-500">
              This is an unsigned preview of the Authority Document. The final
              signed version will include a digital signature, timestamp, and
              verification stamp.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}