import type { DelayReason } from "@/data/delay-reasons/types";
const names:Record<string,string>={"technical-problems":"Tekniset ongelmat","bad-weather":"Huono sää","air-traffic-control":"Lennonjohdon rajoitukset","airline-staff-strike":"Lentoyhtiön henkilöstön lakko","crew-shortage":"Miehistöpula","late-incoming-aircraft":"Myöhässä saapuva lentokone","bird-strike":"Lintutörmäys","airport-closure":"Lentoaseman sulkeminen","security-issue":"Turvallisuusongelma","hidden-manufacturing-defect":"Piilevä valmistusvirhe","operational-reasons":"Operatiiviset syyt"};
const causeCopy:Record<string,{overview:string;rules:string}>={
"technical-problems":{overview:"Lentoyhtiön tavanomaiseen toimintaan kuuluvia teknisiä vikoja ei EU261:n mukaan yleensä pidetä poikkeuksellisina olosuhteina.",rules:"Tavanomaiset tekniset tai mekaaniset ongelmat eivät automaattisesti vapauta lentoyhtiötä korvausvastuusta. Aidosti ulkoinen ja epätavallinen tapahtuma voidaan arvioida toisin."},
"bad-weather":{overview:"Sää voi olla poikkeuksellinen olosuhde, jos olosuhteet todella estävät turvallisen lentotoiminnan tai rajoittavat sitä merkittävästi.",rules:"Sääolosuhteiden ja kyseisen lentohäiriön välillä on oltava todellinen syy-yhteys. Myös lentoyhtiön kohtuulliset toimenpiteet on arvioitava."},
"air-traffic-control":{overview:"Lennonjohdon päätökset ovat yleensä lentoyhtiön määräysvallan ulkopuolella ja voivat olla poikkeuksellisia olosuhteita.",rules:"Lennonjohdon rajoituksen on täytynyt tosiasiallisesti aiheuttaa kyseinen häiriö. Oikeudet huolenpitoon, lipun hinnan palautukseen tai uudelleenreititykseen voivat säilyä siitä riippumatta."},
"airline-staff-strike":{overview:"Lentoyhtiön oman henkilöstön lakko ei automaattisesti ole poikkeuksellinen olosuhde. Sisäisiä ja ulkopuolisten tahojen lakkoja voidaan arvioida oikeudellisesti eri tavoin.",rules:"Keskeistä on erityisesti se, kuka lakkoili. Oman henkilöstön työtaistelu voi kuulua lentoyhtiön normaaliin toimintaan, kun taas ulkopuolisen tahon lakko voidaan arvioida toisin."},
"crew-shortage":{overview:"Henkilöstö- ja varamiehistösuunnittelu kuuluu lähtökohtaisesti lentoyhtiön normaaliin toimintaan. Tavallinen miehistöpula ei muutu poikkeukselliseksi pelkästään sillä perusteella, että sitä kutsutaan miehistöongelmaksi.",rules:"Ratkaisevaa on miehistöpulan alkuperäinen syy. Epätavallinen ulkoinen tapahtuma voi edellyttää toisenlaista arviointia."},
"late-incoming-aircraft":{overview:"Myöhässä saapuva lentokone kuvaa viivästyksen siirtymistä seuraavalle lennolle, ei viivästyksen alkuperäistä oikeudellista syytä.",rules:"Edellisen lennon viivästyksen syy on jäljitettävä. Aiempi poikkeuksellinen tapahtuma voidaan arvioida eri tavoin kuin tavalliset tekniset, henkilöstöön liittyvät tai operatiiviset ongelmat."},
"bird-strike":{overview:"Lintutörmäys on yleensä ulkoinen tapahtuma ja voi olla poikkeuksellinen olosuhde.",rules:"Lentoyhtiön on yhdistettävä lintutörmäys kyseiseen häiriöön ja osoitettava, etteivät kohtuulliset toimenpiteet olisi voineet estää lopullista viivästystä."},
"airport-closure":{overview:"Ulkopuolisen tahon määräämä lentoaseman sulkeminen on yleensä lentoyhtiön määräysvallan ulkopuolella ja voi olla poikkeuksellinen olosuhde.",rules:"Vakiokorvaus sekä oikeudet uudelleenreititykseen, lipun hinnan palautukseen ja huolenpitoon arvioidaan erikseen. Kohtuulliset vaihtoehdot voivat olla merkityksellisiä myös lentoaseman sulkemisen yhteydessä."},
"security-issue":{overview:"Vakavat turvallisuusuhat ja ulkopuoliset turvallisuustoimet voivat olla poikkeuksellisia olosuhteita.",rules:"Yleinen viittaus turvallisuuteen ei riitä. Konkreettinen tapahtuma, sen yhteys lentoon ja lentoyhtiön toimenpiteet on arvioitava."},
"hidden-manufacturing-defect":{overview:"Valmistajan tai toimivaltaisen viranomaisen toteama piilevä valmistusvirhe voi tietyissä tilanteissa olla poikkeuksellinen. Tämä ryhmä on selvästi tavallisia teknisiä vikoja suppeampi.",rules:"Lentoyhtiön on osoitettava todellinen epätavallinen valmistusvirhe ja sen yhteys häiriöön."},
"operational-reasons":{overview:"”Operatiiviset syyt” on laaja kuvaus eikä sellaisenaan poikkeuksellinen olosuhde. Todellinen syy on selvitettävä.",rules:"Taustalla voi olla miehistöön, lentokonekiertoon, suunnitteluun, maahuolintaan tai tekniikkaan liittyviä ongelmia. EU261-arvioinnin on perustuttava todelliseen syyhyn ja tapahtumien kulkuun."}};
export function buildFinnishDelayReason(delayReason:DelayReason):DelayReason{const title=names[delayReason.slug]??delayReason.title,copy=causeCopy[delayReason.slug];if(!copy)return delayReason;const extraordinary=delayReason.extraordinaryCircumstance;return{...delayReason,title,description:`Lue, milloin ${title.toLowerCase()} voivat vaikuttaa EU261:n mukaiseen lentokorvaukseen ja mitä muita lentomatkustajan oikeuksia voi olla.`,overview:copy.overview,passengerRights:extraordinary?"Vaikka poikkeuksellinen olosuhde estäisi vakiokorvauksen, oikeudet huolenpitoon, uudelleenreititykseen tai lipun hinnan palautukseen voivat säilyä.":"Jos häiriö johti vähintään kolmen tunnin myöhästymiseen lopullisessa määränpäässä, korvaukseen oikeuttavaan peruutukseen tai muuhun korvattavaan tapahtumaan, EU261 voi antaa oikeuden korvaukseen.",compensationRules:copy.rules,statisticsIntro:`Kun syynä ovat ${title.toLowerCase()}, on arvioitava todellinen syy, vaikutus kyseiseen lentoon ja lentoyhtiön toimenpiteet.`,statistics:[{label:"Poikkeuksellinen olosuhde",value:extraordinary?"Mahdollinen":"Ei yleensä",description:"Konkreettinen syy ja syy-yhteys on arvioitava tapauskohtaisesti."},{label:"EU261-korvaus",value:extraordinary?"Tapauskohtainen":"Voi olla mahdollinen",description:"Soveltamisala, viivästys tai peruutus ja syy arvioidaan yhdessä."},{label:"Huolenpito ja uudelleenreititys",value:"Erilliset oikeudet",description:"Nämä oikeudet voivat säilyä, vaikka vakiokorvausta ei maksettaisi."}],timelineIntro:`Tapauksessa, jossa syynä ovat ${title.toLowerCase()}, ilmoitettu syy on yhdistettävä todelliseen lentohäiriöön.`,timeline:[{title:"Häiriö tapahtuu",description:"Lento viivästyy, perutaan tai häiriintyy muulla tavalla."},{title:"Syy selvitetään",description:`Tarkistamme ${title.toLowerCase()} koskevat tiedot ja tapahtumien aikajanan.`},{title:"Syy-yhteys ja toimenpiteet arvioidaan",description:"Arvioimme, selittääkö syy todella häiriön ja mitä kohtuullisia toimenpiteitä oli käytettävissä."},{title:"Lentomatkustajan oikeudet arvioidaan",description:"Vakiokorvaus sekä erilliset oikeudet huolenpitoon, uudelleenreititykseen tai lipun hinnan palautukseen arvioidaan erikseen."}],faqIntro:`Usein kysyttyjä kysymyksiä aiheesta ${title.toLowerCase()} ja lentokorvaus.`,faq:[{question:`Ovatko ${title.toLowerCase()} aina poikkeuksellisia olosuhteita?`,answer:extraordinary?"Eivät automaattisesti. Tapahtuman on täytettävä oikeudelliset edellytykset ja sen on täytynyt todella aiheuttaa kyseinen häiriö.":"Ryhmänä eivät yleensä ole, mutta todellinen perussyy ja tapauksen olosuhteet on silti arvioitava."},{question:"Voinko silti saada uudelleenreitityksen tai huolenpitoa?",answer:"Kyllä. Oikeudet uudelleenreititykseen, lipun hinnan palautukseen ja huolenpitoon arvioidaan erillään vakiokorvauksesta."},{question:"Mitä lentoyhtiön pitäisi osoittaa?",answer:"Konkreettinen syy, sen yhteys lentoon ja toteutetut kohtuulliset toimenpiteet."}]};}
