import { Link } from "@/i18n/navigation";
import type { Locale } from "@/i18n/routing";

type Competitor = "refly" | "airhelp";

const competitorData = {
  refly: { name:"ReFly", fee:33, legal:50, source:"https://www.refly.org/terms-and-conditions.html" },
  airhelp: { name:"AirHelp", fee:35, legal:50, source:"https://www.airhelp.com/en-int/our-fees/" },
} as const;

const text = {
 en:{checked:"Fee comparison · checked 29 September 2026",intro:"Both services handle flight compensation claims on a no-upfront-fee basis. A key difference is the published standard fee.",ourFee:"FlightClaimly standard fee",theirFee:"published standard fee",keep:"You keep",difference:"more remains with the passenger under FlightClaimly's published standard fee.",side:"Side-by-side",title:"Published fees compared",body:"This comparison uses each provider's own published pricing. It compares fees, not claim outcomes, speed or overall service quality.",comparison:"Comparison",standard:"Standard fee",noUpfront:"No upfront fee",noRecovery:"No recovery / no standard fee",legal:"Fee when legal action is required",legalKeep:"You keep from €600 if legal action applies",yes:"Yes",example:"€600 example",diffTitle:"difference at the standard fee",legalLabel:"Legal action",legalTitle:"The fee difference can become larger",sources:"Sources",verify:"Verify the numbers yourself",fees:"FlightClaimly fees & comparison",official:"official fees",faq:"FAQ",faqTitle:"comparison questions",final:"Keep 80% of your compensation.",cta:"Check my flight",note:"Providers can change their pricing. Exceptional case-specific costs may also apply. Always review the current terms before submitting a claim."},
 sv:{checked:"Avgiftsjämförelse · kontrollerad 29 september 2026",intro:"Båda tjänsterna hanterar krav på flygkompensation utan förskottsavgift. En viktig skillnad är den publicerade standardavgiften.",ourFee:"FlightClaimlys standardavgift",theirFee:"publicerad standardavgift",keep:"Du behåller",difference:"mer stannar hos passageraren med FlightClaimlys publicerade standardavgift.",side:"Sida vid sida",title:"Publicerade avgifter jämförda",body:"Jämförelsen använder respektive bolags egen publicerade prissättning. Den jämför avgifter, inte resultat, handläggningstid eller total servicekvalitet.",comparison:"Jämförelse",standard:"Standardavgift",noUpfront:"Ingen förskottsavgift",noRecovery:"Ingen ersättning / ingen standardavgift",legal:"Avgift när juridiska åtgärder krävs",legalKeep:"Du behåller av €600 vid juridiska åtgärder",yes:"Ja",example:"Exempel €600",diffTitle:"skillnad med standardavgiften",legalLabel:"Juridiska åtgärder",legalTitle:"Avgiftsskillnaden kan bli större",sources:"Källor",verify:"Kontrollera siffrorna själv",fees:"FlightClaimlys avgifter & jämförelse",official:"officiella avgifter",faq:"Vanliga frågor",faqTitle:"frågor om jämförelsen",final:"Behåll 80% av din ersättning.",cta:"Kontrollera mitt flyg",note:"Bolag kan ändra sina priser. Ärendespecifika kostnader kan också förekomma. Läs alltid aktuella villkor innan du skickar in ett krav."},
 da:{checked:"Gebyrsammenligning · kontrolleret 29. september 2026",intro:"Begge tjenester håndterer flykompensationskrav uden betaling på forhånd. En vigtig forskel er det offentliggjorte standardgebyr.",ourFee:"FlightClaimlys standardgebyr",theirFee:"offentliggjort standardgebyr",keep:"Du beholder",difference:"mere bliver hos passageren med FlightClaimlys offentliggjorte standardgebyr.",side:"Side om side",title:"Offentliggjorte gebyrer sammenlignet",body:"Sammenligningen bruger hver udbyders egen offentliggjorte prissætning. Den sammenligner gebyrer, ikke resultater, hastighed eller samlet servicekvalitet.",comparison:"Sammenligning",standard:"Standardgebyr",noUpfront:"Ingen betaling på forhånd",noRecovery:"Ingen kompensation / intet standardgebyr",legal:"Gebyr når juridiske skridt kræves",legalKeep:"Du beholder af €600 ved juridiske skridt",yes:"Ja",example:"€600 eksempel",diffTitle:"forskel ved standardgebyret",legalLabel:"Juridiske skridt",legalTitle:"Gebyrforskellen kan blive større",sources:"Kilder",verify:"Kontrollér tallene selv",fees:"FlightClaimly gebyrer & sammenligning",official:"officielle gebyrer",faq:"FAQ",faqTitle:"spørgsmål om sammenligningen",final:"Behold 80% af din kompensation.",cta:"Tjek mit fly",note:"Udbydere kan ændre priser. Sagsspecifikke omkostninger kan også forekomme. Læs altid de aktuelle vilkår."},
 de:{checked:"Gebührenvergleich · geprüft am 29. September 2026",intro:"Beide Dienste bearbeiten Fluggastentschädigungsansprüche ohne Vorauszahlung. Ein wichtiger Unterschied ist die veröffentlichte Standardgebühr.",ourFee:"FlightClaimly Standardgebühr",theirFee:"veröffentlichte Standardgebühr",keep:"Sie behalten",difference:"mehr bleibt dem Passagier bei der veröffentlichten Standardgebühr von FlightClaimly.",side:"Direktvergleich",title:"Veröffentlichte Gebühren im Vergleich",body:"Der Vergleich nutzt die veröffentlichten Preise beider Anbieter. Verglichen werden Gebühren, nicht Erfolgsquoten, Geschwindigkeit oder die gesamte Servicequalität.",comparison:"Vergleich",standard:"Standardgebühr",noUpfront:"Keine Vorauszahlung",noRecovery:"Keine Entschädigung / keine Standardgebühr",legal:"Gebühr bei rechtlichen Schritten",legalKeep:"Von €600 behalten bei rechtlichen Schritten",yes:"Ja",example:"€600 Beispiel",diffTitle:"Unterschied bei der Standardgebühr",legalLabel:"Rechtliche Schritte",legalTitle:"Der Gebührenunterschied kann größer werden",sources:"Quellen",verify:"Zahlen selbst prüfen",fees:"FlightClaimly Gebühren & Vergleich",official:"offizielle Gebühren",faq:"FAQ",faqTitle:"Fragen zum Vergleich",final:"Behalten Sie 80% Ihrer Entschädigung.",cta:"Flug prüfen",note:"Anbieter können Preise ändern. Fallspezifische Kosten können ebenfalls anfallen. Prüfen Sie vor Einreichung stets die aktuellen Bedingungen."},
 nl:{checked:"Kostenvergelijking · gecontroleerd 29 september 2026",intro:"Beide diensten behandelen vluchtcompensatieclaims zonder vooruitbetaling. Een belangrijk verschil is het gepubliceerde standaardtarief.",ourFee:"Standaardtarief FlightClaimly",theirFee:"gepubliceerd standaardtarief",keep:"U houdt",difference:"meer blijft bij de passagier onder het gepubliceerde standaardtarief van FlightClaimly.",side:"Naast elkaar",title:"Gepubliceerde tarieven vergeleken",body:"Deze vergelijking gebruikt de eigen gepubliceerde prijzen van elke aanbieder. We vergelijken tarieven, niet resultaten, snelheid of totale servicekwaliteit.",comparison:"Vergelijking",standard:"Standaardtarief",noUpfront:"Geen vooruitbetaling",noRecovery:"Geen vergoeding / geen standaardtarief",legal:"Tarief wanneer juridische actie nodig is",legalKeep:"U houdt van €600 bij juridische actie",yes:"Ja",example:"€600 voorbeeld",diffTitle:"verschil bij het standaardtarief",legalLabel:"Juridische actie",legalTitle:"Het tariefverschil kan groter worden",sources:"Bronnen",verify:"Controleer de cijfers zelf",fees:"FlightClaimly tarieven & vergelijking",official:"officiële tarieven",faq:"FAQ",faqTitle:"vragen over de vergelijking",final:"Houd 80% van uw compensatie.",cta:"Controleer mijn vlucht",note:"Aanbieders kunnen prijzen wijzigen. Zaakspecifieke kosten kunnen ook gelden. Controleer altijd de actuele voorwaarden."},
 pl:{checked:"Porównanie opłat · sprawdzono 29 września 2026",intro:"Obie usługi prowadzą roszczenia o odszkodowanie bez opłaty z góry. Ważną różnicą jest opublikowana standardowa prowizja.",ourFee:"Standardowa opłata FlightClaimly",theirFee:"opublikowana standardowa opłata",keep:"Dla Ciebie",difference:"więcej pozostaje pasażerowi przy opublikowanej standardowej opłacie FlightClaimly.",side:"Porównanie",title:"Porównanie opublikowanych opłat",body:"Porównanie wykorzystuje oficjalnie opublikowane ceny obu firm. Porównujemy opłaty, a nie wyniki spraw, szybkość ani ogólną jakość usług.",comparison:"Porównanie",standard:"Standardowa opłata",noUpfront:"Brak opłaty z góry",noRecovery:"Brak odszkodowania / brak standardowej opłaty",legal:"Opłata przy działaniach prawnych",legalKeep:"Z €600 zostaje przy działaniach prawnych",yes:"Tak",example:"Przykład €600",diffTitle:"różnicy przy standardowej opłacie",legalLabel:"Działania prawne",legalTitle:"Różnica w opłatach może być większa",sources:"Źródła",verify:"Sprawdź liczby samodzielnie",fees:"Opłaty FlightClaimly i porównanie",official:"oficjalne opłaty",faq:"FAQ",faqTitle:"pytania o porównanie",final:"Zachowaj 80% odszkodowania.",cta:"Sprawdź mój lot",note:"Firmy mogą zmieniać ceny. Mogą wystąpić koszty zależne od sprawy. Zawsze sprawdź aktualne warunki."},
 fi:{checked:"Palkkiovertailu · tarkistettu 29.9.2026",intro:"Molemmat palvelut hoitavat lentokorvausvaatimuksia ilman ennakkomaksua. Keskeinen ero on julkaistu vakiopalkkio.",ourFee:"FlightClaimlyn vakiopalkkio",theirFee:"julkaistu vakiopalkkio",keep:"Sinulle jää",difference:"enemmän jää matkustajalle FlightClaimlyn julkaistulla vakiopalkkiolla.",side:"Rinnakkain",title:"Julkaistut palkkiot vertailussa",body:"Vertailu käyttää kummankin palvelun omia julkaistuja hintoja. Se vertaa palkkioita, ei tuloksia, nopeutta tai palvelun kokonaislaatua.",comparison:"Vertailu",standard:"Vakiopalkkio",noUpfront:"Ei ennakkomaksua",noRecovery:"Ei korvausta / ei vakiopalkkiota",legal:"Palkkio oikeustoimissa",legalKeep:"€600:sta jää oikeustoimissa",yes:"Kyllä",example:"€600 esimerkki",diffTitle:"ero vakiopalkkiolla",legalLabel:"Oikeustoimet",legalTitle:"Palkkioero voi kasvaa",sources:"Lähteet",verify:"Tarkista luvut itse",fees:"FlightClaimlyn palkkiot & vertailu",official:"viralliset palkkiot",faq:"UKK",faqTitle:"vertailukysymykset",final:"Pidä 80% korvauksestasi.",cta:"Tarkista lentoni",note:"Palvelut voivat muuttaa hintojaan. Tapauskohtaisia kuluja voi myös olla. Tarkista aina ajantasaiset ehdot."},
 es:{checked:"Comparación de comisiones · comprobado el 29 de septiembre de 2026",intro:"Ambos servicios gestionan reclamaciones de compensación sin pago por adelantado. Una diferencia importante es la comisión estándar publicada.",ourFee:"Comisión estándar de FlightClaimly",theirFee:"comisión estándar publicada",keep:"Tú conservas",difference:"más queda para el pasajero con la comisión estándar publicada de FlightClaimly.",side:"Comparación directa",title:"Comisiones publicadas comparadas",body:"La comparación utiliza los precios publicados por cada proveedor. Compara comisiones, no resultados, rapidez ni calidad global del servicio.",comparison:"Comparación",standard:"Comisión estándar",noUpfront:"Sin pago por adelantado",noRecovery:"Sin compensación / sin comisión estándar",legal:"Comisión si se requiere acción legal",legalKeep:"Conservas de €600 con acción legal",yes:"Sí",example:"Ejemplo €600",diffTitle:"de diferencia con la comisión estándar",legalLabel:"Acción legal",legalTitle:"La diferencia puede ser mayor",sources:"Fuentes",verify:"Comprueba las cifras",fees:"Comisiones y comparación de FlightClaimly",official:"comisiones oficiales",faq:"FAQ",faqTitle:"preguntas sobre la comparación",final:"Conserva el 80% de tu compensación.",cta:"Comprobar mi vuelo",note:"Los proveedores pueden cambiar sus precios. También pueden existir costes específicos del caso. Revisa siempre las condiciones vigentes."},
} satisfies Record<Locale, Record<string,string>>;

export function ComparisonPage({ locale, competitor }: { locale: Locale; competitor: Competitor }) {
 const d=competitorData[competitor], t=text[locale];
 const money = (value: number) => Number(value.toFixed(2));
 const theirKeep=money(600*(1-d.fee/100)), diff=money(480-theirKeep), theirLegalKeep=money(600*(1-d.legal/100));
 const faq=[
  {q:`${d.name} vs FlightClaimly: what is the standard fee?`,a:`FlightClaimly's standard fee is 20% including VAT. ${d.name}'s published standard fee is ${d.fee}% including VAT.`},
  {q:`How much do I keep from €600?`,a:`At the published standard rates, FlightClaimly leaves €480 and ${d.name} leaves €${theirKeep} from a €600 recovery.`},
  {q:`What if legal action is required?`,a:`FlightClaimly states a total fee of 30% including VAT when legal action is required. ${d.name}'s published legal-action total is ${d.legal}% including VAT.`},
 ];
 const schema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(x=>({"@type":"Question",name:x.q,acceptedAnswer:{"@type":"Answer",text:x.a}}))};
 return <main className="min-h-screen bg-white text-slate-950">
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
  <section className="bg-[#061329] text-white"><div className="mx-auto max-w-6xl px-6 py-6 flex items-center justify-between"><Link href="/" className="text-2xl font-extrabold tracking-tight">FLIGHTCLAIMLY</Link><Link href="/" className="rounded-full bg-emerald-400 px-5 py-3 text-sm font-bold text-slate-950">{t.cta}</Link></div>
  <div className="mx-auto max-w-6xl px-6 py-20 lg:py-28"><p className="mb-5 text-xs font-bold uppercase tracking-[.25em] text-emerald-300">{t.checked}</p><h1 className="max-w-4xl text-5xl font-extrabold tracking-tight sm:text-6xl lg:text-7xl">FlightClaimly vs {d.name}</h1><p className="mt-6 max-w-3xl text-xl leading-8 text-slate-300">{t.intro} FlightClaimly: 20% incl. VAT. {d.name}: {d.fee}% incl. VAT.</p>
  <div className="mt-10 grid max-w-3xl gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-slate-700 bg-slate-900/50 p-6"><p className="text-sm text-slate-400">{t.ourFee}</p><p className="mt-2 text-5xl font-extrabold text-emerald-300">20%</p><p className="mt-2 text-sm text-slate-300">{t.keep} €480 / €600</p></div><div className="rounded-2xl border border-slate-700 bg-slate-900/50 p-6"><p className="text-sm text-slate-400">{d.name} {t.theirFee}</p><p className="mt-2 text-5xl font-extrabold">{d.fee}%</p><p className="mt-2 text-sm text-slate-300">{t.keep} €{theirKeep} / €600</p></div></div><p className="mt-6 text-sm text-slate-400">€{diff} {t.difference}</p></div></section>
  <section className="mx-auto max-w-6xl px-6 py-20"><p className="text-xs font-bold uppercase tracking-[.22em] text-emerald-700">{t.side}</p><h2 className="mt-3 text-4xl font-extrabold">{t.title}</h2><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-600">{t.body}</p><div className="mt-10 overflow-x-auto rounded-2xl border border-slate-200"><table className="w-full min-w-[720px] text-left"><thead className="bg-slate-50"><tr><th className="p-5">{t.comparison}</th><th className="p-5">FlightClaimly</th><th className="p-5">{d.name}</th></tr></thead><tbody>{[[t.standard,"20% incl. VAT",`${d.fee}% incl. VAT`],[t.keep+" €600","€480",`€${theirKeep}`],[t.noUpfront,t.yes,t.yes],[t.noRecovery,t.yes,t.yes],[t.legal,"30% incl. VAT",`${d.legal}% incl. VAT`],[t.legalKeep,"€420",`€${theirLegalKeep}`]].map(r=><tr key={r[0]} className="border-t border-slate-200"><th className="p-5 font-semibold">{r[0]}</th><td className="p-5 font-bold text-emerald-700">{r[1]}</td><td className="p-5">{r[2]}</td></tr>)}</tbody></table></div><p className="mt-5 text-sm text-slate-500">{t.note}</p></section>
  <section className="bg-slate-50"><div className="mx-auto grid max-w-6xl gap-10 px-6 py-20 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-emerald-700">{t.example}</p><h2 className="mt-3 text-4xl font-extrabold">€{diff} {t.diffTitle}</h2><p className="mt-5 text-lg leading-8 text-slate-600">FlightClaimly: €600 − €120 = €480. {d.name}: €600 − €{600-theirKeep} = €{theirKeep}.</p></div><div className="rounded-3xl bg-[#061329] p-8 text-white"><div className="flex justify-between border-b border-slate-700 pb-5"><span>€600</span><strong>100%</strong></div><div className="flex justify-between border-b border-slate-700 py-5"><span>FlightClaimly</span><strong>− €120</strong></div><div className="flex justify-between pt-5 text-2xl"><strong>{t.keep}</strong><strong className="text-emerald-300">€480</strong></div></div></div></section>
  <section className="mx-auto max-w-6xl px-6 py-20"><p className="text-xs font-bold uppercase tracking-[.22em] text-emerald-700">{t.legalLabel}</p><h2 className="mt-3 text-4xl font-extrabold">{t.legalTitle}</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">FlightClaimly: 30% incl. VAT → €420 / €600. {d.name}: {d.legal}% incl. VAT → €{theirLegalKeep} / €600.</p></section>
  <section className="bg-slate-50"><div className="mx-auto max-w-6xl px-6 py-20"><p className="text-xs font-bold uppercase tracking-[.22em] text-emerald-700">{t.sources}</p><h2 className="mt-3 text-4xl font-extrabold">{t.verify}</h2><div className="mt-8 grid gap-5 md:grid-cols-2"><Link href="/fees" className="rounded-2xl border bg-white p-6 font-bold">{t.fees} →</Link><a href={d.source} target="_blank" rel="noopener noreferrer" className="rounded-2xl border bg-white p-6 font-bold">{d.name} {t.official} →</a></div></div></section>
  <section className="mx-auto max-w-4xl px-6 py-20"><p className="text-xs font-bold uppercase tracking-[.22em] text-emerald-700">{t.faq}</p><h2 className="mt-3 text-4xl font-extrabold">FlightClaimly vs {d.name}: {t.faqTitle}</h2><div className="mt-8 divide-y border-y">{faq.map(x=><div key={x.q} className="py-7"><h3 className="text-xl font-bold">{x.q}</h3><p className="mt-3 leading-7 text-slate-600">{x.a}</p></div>)}</div></section>
  <section className="bg-[#061329] text-white"><div className="mx-auto max-w-6xl px-6 py-20 text-center"><h2 className="text-4xl font-extrabold sm:text-5xl">{t.final}</h2><Link href="/" className="mt-8 inline-block rounded-full bg-emerald-400 px-7 py-4 font-bold text-slate-950">{t.cta}</Link></div></section>
 </main>;
}