import assert from "node:assert/strict";
import { publishableFlightNumbers } from "../src/lib/flight-numbers/catalog";
import { buildDanishFlightNumberLocalization, buildGermanFlightNumberLocalization, buildLocalizedLanguageAlternates, buildPolishFlightNumberLocalization, buildSwedishFlightNumberLocalization, getLocaleDefinition, isLocalizationPublishable, resolveKnowledgeLocalization, type KnowledgeLocalization, type LocalizedSeoVariant } from "../src/lib/localization";
const canonical = { entityType: "flight-number" as const, entitySlug: "sk1421", metadata: { title: "SK1421 flight compensation | FlightClaimly", description: "Canonical English description." }, content: { intro: "Canonical English intro." } };
const reviewedSwedish: KnowledgeLocalization = { entityType: "flight-number", entitySlug: "sk1421", locale: "sv", source: "human", status: "publishable", metadata: { title: "SK1421 flygersättning | FlightClaimly", description: "Granskad svensk beskrivning." }, content: { intro: "Granskad svensk introduktion." }, quality: { metadataReviewed: true, terminologyReviewed: true, legalMeaningReviewed: true, contentReviewed: true } };
const incompleteGerman: KnowledgeLocalization = { entityType: "flight-number", entitySlug: "sk1421", locale: "de", source: "machine-assisted", status: "publishable", metadata: { title: "SK1421 Flugentschädigung | FlightClaimly", description: "Noch nicht vollständig geprüfte deutsche Beschreibung." }, quality: { metadataReviewed: true, terminologyReviewed: false, legalMeaningReviewed: false, contentReviewed: false } };
const english = resolveKnowledgeLocalization({ canonical, locale: "en" }); assert.equal(english.publicationStatus, "publishable"); assert.equal(english.source, "human");
const missingFinnish = resolveKnowledgeLocalization({ canonical, locale: "fi" }); assert.equal(missingFinnish.source, "canonical-fallback"); assert.equal(missingFinnish.publicationStatus, "review-required"); assert.equal(missingFinnish.metadata.title, canonical.metadata.title);
const swedish = resolveKnowledgeLocalization({ canonical, locale: "sv", localization: reviewedSwedish }); assert.equal(swedish.publicationStatus, "publishable"); assert.equal(isLocalizationPublishable(reviewedSwedish), true);
const germanIncomplete = resolveKnowledgeLocalization({ canonical, locale: "de", localization: incompleteGerman }); assert.equal(germanIncomplete.publicationStatus, "review-required"); assert.equal(isLocalizationPublishable(incompleteGerman), false);
const variants: LocalizedSeoVariant[] = [{ locale: "en", path: "flight-numbers/sk1421", resolution: english }, { locale: "sv", path: "flight-numbers/sk1421", resolution: swedish }, { locale: "de", path: "flight-numbers/sk1421", resolution: germanIncomplete }, { locale: "fi", path: "flight-numbers/sk1421", resolution: missingFinnish }];
const alternates = buildLocalizedLanguageAlternates(variants); assert.deepEqual(Object.keys(alternates).sort(), ["en", "sv"]); assert.equal(alternates.de, undefined); assert.equal(alternates.fi, undefined);
const pilot = publishableFlightNumbers[0]; assert.ok(pilot);
const sv = buildSwedishFlightNumberLocalization(pilot); assert.equal(isLocalizationPublishable(sv), true); assert.match(sv.metadata.title, /flygersättning/i);
const da = buildDanishFlightNumberLocalization(pilot); assert.equal(isLocalizationPublishable(da), true); assert.match(da.metadata.title, /flykompensation/i);
const pl = buildPolishFlightNumberLocalization(pilot); assert.equal(isLocalizationPublishable(pl), true); assert.match(pl.metadata.title, /odszkodowanie/i);
const de = buildGermanFlightNumberLocalization(pilot); assert.equal(de.locale, "de"); assert.equal(de.status, "publishable"); assert.equal(isLocalizationPublishable(de), true); assert.match(de.metadata.title, /Flugentschädigung/i); assert.match(de.metadata.description, /Verspätung oder Annullierung/i); assert.ok(de.content?.faq?.length); assert.ok(de.content?.timeline?.length);
assert.equal(getLocaleDefinition("sv").labels.yes, "Ja"); assert.equal(getLocaleDefinition("da").labels.flightNumbers, "Flynumre"); assert.equal(getLocaleDefinition("pl").labels.yes, "Tak"); assert.equal(getLocaleDefinition("de").labels.yes, "Ja"); assert.equal(getLocaleDefinition("de").labels.flightNumbers, "Flugnummern");
const euOnly = publishableFlightNumbers.find((f) => f.eu261Eligible && !f.uk261Eligible); const ukOnly = publishableFlightNumbers.find((f) => !f.eu261Eligible && f.uk261Eligible); const both = publishableFlightNumbers.find((f) => f.eu261Eligible && f.uk261Eligible); const neither = publishableFlightNumbers.find((f) => !f.eu261Eligible && !f.uk261Eligible); assert.ok(euOnly); assert.ok(ukOnly); assert.ok(both); assert.ok(neither);
for (const build of [buildSwedishFlightNumberLocalization, buildDanishFlightNumberLocalization, buildPolishFlightNumberLocalization, buildGermanFlightNumberLocalization]) {
  const eu = JSON.stringify({ amounts: build(euOnly).content?.compensationAmounts, statistics: build(euOnly).content?.statistics }); const uk = JSON.stringify({ amounts: build(ukOnly).content?.compensationAmounts, statistics: build(ukOnly).content?.statistics }); const dual = JSON.stringify({ amounts: build(both).content?.compensationAmounts, statistics: build(both).content?.statistics }); const neutral = JSON.stringify({ metadata: build(neither).metadata, passengerRights: build(neither).content?.passengerRights, amounts: build(neither).content?.compensationAmounts, statistics: build(neither).content?.statistics, claimProcess: build(neither).content?.claimProcess, faq: build(neither).content?.faq });
  assert.match(eu, /€600/); assert.doesNotMatch(eu, /£520/); assert.match(uk, /£520/); assert.doesNotMatch(uk, /€600/); assert.match(dual, /€600/); assert.match(dual, /£520/); assert.doesNotMatch(neutral, /€250|€400|€600|£220|£350|£520/);
}
assert.match(JSON.stringify(buildSwedishFlightNumberLocalization(neither)), /tillämpliga regler|vilket regelverk|regelverk som gäller/i); assert.match(JSON.stringify(buildDanishFlightNumberLocalization(neither)), /relevante regler|hvilke regler|regelsæt/i); assert.match(JSON.stringify(buildPolishFlightNumberLocalization(neither)), /właściw|przepis|zależy od przypadku|do ustalenia/i); assert.match(JSON.stringify(buildGermanFlightNumberLocalization(neither)), /anwendbar|Einzelfall|Zu prüfen|Regelwerk/i);
console.log("Localization Engine architecture audit"); console.log("PASS — canonical fallback isolation, quality gates, publishable-only hreflang, Swedish, Danish, Polish and German flight-number localization and EU261/UK261 compensation profiles behave as expected.");
